### ISSUE TITLE
Dark mode has a flicker on load

### ISSUE THREAD

**Issue by vinyll** [zkreations/docs#9]
When browsing from a page to another in dark mode, the page first loads in light mode for a fraction of a second then goes dark.
It makes a weird disturbing flickering effect.

**Comment by danieIabel** [comment]
Sure! Here's the translation in clear and professional English:

---

Good morning. Thank you for informing me. I’ve run some tests and couldn’t reproduce the issue you mentioned. Please fill out the following information so I can try to replicate the problem:

**Steps to Reproduce**
Steps to reproduce the behavior, for example:

1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See the error

**Expected Behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, please add screenshots to help explain your issue.

**Desktop (please complete the following information if applicable):**

* OS: \[e.g. iOS 14, Windows 11, etc.]
* Browser: \[e.g. Chrome, Safari, etc.]
* Version: \[e.g. 22, 99, etc.]

**Smartphone (please complete the following information if applicable):**

* Device: \[e.g. iPhone 6, Huawei Nova 5T, etc.]
* OS: \[e.g. iOS 8.1, Android 11, etc.]
* Browser: \[e.g. Stock Browser, Chrome, Safari, etc.]
* Version: \[e.g. 22, 99, etc.]

**Additional Context (Optional)**
Add any other context about the problem here.

---

Let me know if you want it in a different tone (e.g., more formal or friendly).

**Comment by danieIabel** [comment]
Good morning. Thank you for informing me. I’ve run some tests and couldn’t reproduce the issue you mentioned. Please fill out the following information so I can try to replicate the problem:

**Steps to Reproduce**
Steps to reproduce the behavior, for example:

1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See the error

**Expected Behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, please add screenshots to help explain your issue.

**Desktop (please complete the following information if applicable):**

* OS: \[e.g. iOS 14, Windows 11, etc.]
* Browser: \[e.g. Chrome, Safari, etc.]
* Version: \[e.g. 22, 99, etc.]

**Smartphone (please complete the following information if applicable):**

* Device: \[e.g. iPhone 6, Huawei Nova 5T, etc.]
* OS: \[e.g. iOS 8.1, Android 11, etc.]
* Browser: \[e.g. Stock Browser, Chrome, Safari, etc.]
* Version: \[e.g. 22, 99, etc.]

**Additional Context (Optional)**
Add any other context about the problem here.

**Comment by vinyll** [comment]
Here's a screen video I just made.
Using Firefiox 140 on a latest Macbook.

https://github.com/user-attachments/assets/1dacd65e-8544-44f6-8bc9-1dd0ae592faf

**Comment by vinyll** [comment]
Brave has less of that flickering.
However you can reproduce by going to https://hudocs.com/1.0/starting/ **in dark mode** and force refreshing with no cache (Cmd+Shift+R on a Mac).

This is using Brave 1.78:
https://github.com/user-attachments/assets/b8255839-0f9b-4a52-b881-c2d6e6fd56c1

**Comment by danieIabel** [comment]
Thank you very much for letting me know. I’ve been able to confirm that the issue exists and I’m already working on a solution.

**Comment by danieIabel** [comment]
Good afternoon again. I've fixed the problem; please check the demo to ensure everything works as expected. You'll need to force a cache reload to see the latest changes.

**Comment by vinyll** [comment]
I still have the issue with Firefox and Brave despite browsing in Private Mode to ensure no cache is active.

## Firefox

https://github.com/user-attachments/assets/f072de9b-2d4a-448b-bdff-af7dcdba9503

## Brave

It occurs less often when browsing and easy to reproduce again with Cmd+Shift+R:

https://github.com/user-attachments/assets/69ea7063-bda6-4001-a50f-d74967dc52a3

**Comment by vinyll** [comment]
One more hint: in our usecase (https://lego.js.org/) using Firefox, we have only that flickering when clicking on the button "Version 1 - Stable".

https://github.com/user-attachments/assets/d3af483b-aaab-4a24-b711-7e308afb4bfd

**Comment by danieIabel** [comment]
Good morning, my friend. On your page https://lego.js.org/, you're not using the latest version where the issue has been fixed. I recommend updating it so the test works correctly.

Regarding the demo page, the initial flash you might sometimes notice is due to the response time of my own server (Netlife). When a page hasn’t loaded because the server hasn’t responded yet, you'll see a white background (if your device uses a light theme) or a black background (if your device uses dark mode at the OS level). That’s what I’ve been able to confirm so far.
